EU_MEMBER_STATES = (
    "austria",
    "belgium",
    "bulgaria",
    "croatia",
    "cyprus",
    "czechia",
    "czech republic",
    "denmark",
    "estonia",
    "finland",
    "france",
    "germany",
    "greece",
    "hungary",
    "ireland",
    "italy",
    "latvia",
    "lithuania",
    "luxembourg",
    "malta",
    "netherlands",
    "poland",
    "portugal",
    "romania",
    "slovakia",
    "slovenia",
    "spain",
    "sweden",
)


EU_REGION_CUSTOM = [
    "emea",
    "western europe",
    "nordics",
    "benelux",
    "dach",
    "uk&i",
    "uk & ireland",
    "uk and ireland",
]

UK_KEYWORDS = (
    "united kingdom",
    "uk only",
    "uk-based",
    "uk based",
    "britain",
    "london",
    "england",
    "scotland",
    "wales",
    "northern ireland",
)


COUNTRY_ALIASES = {
    "deutschland": "germany",
    "de": "germany",
    "fr": "france",
    "nl": "netherlands",
    "niederlande": "netherlands",
    "es": "spain",
    "spanien": "spain",
    "it": "italy",
    "italien": "italy",
    "ie": "ireland",
    "irland": "ireland",
    "pl": "poland",
    "polen": "poland",
    "pt": "portugal",
    "belgia": "belgium",
    "belgique": "belgium",
    "belgien": "belgium",
    "austria": "austria",
    "österreich": "austria",
    "at": "austria",
    "cz": "czech republic",
    "czechia": "czech republic",
    "slovakia": "slovakia",
    "slovensko": "slovakia",
    "sk": "slovakia",
    # Największe miasta mapujące bezpośrednio na kraje EU
    "berlin": "germany",
    "munich": "germany",
    "münchen": "germany",
    "hamburg": "germany",
    "frankfurt": "germany",
    "paris": "france",
    "lyon": "france",
    "marseille": "france",
    "toulouse": "france",
    "madrid": "spain",
    "barcelona": "spain",
    "valencia": "spain",
    "seville": "spain",
    "rome": "italy",
    "milan": "italy",
    "naples": "italy",
    "turin": "italy",
    "warsaw": "poland",
    "warszawa": "poland",
    "krakow": "poland",
    "kraków": "poland",
    "wroclaw": "poland",
    "wrocław": "poland",
    "amsterdam": "netherlands",
    "rotterdam": "netherlands",
    "the hague": "netherlands",
    "utrecht": "netherlands",
    "stockholm": "sweden",
    "gothenburg": "sweden",
    "malmo": "sweden",
    "malmö": "sweden",
    "dublin": "ireland",
    "cork": "ireland",
    "galway": "ireland",
    "lisbon": "portugal",
    "porto": "portugal",
    "braga": "portugal",
    "vienna": "austria",
    "wien": "austria",
    "salzburg": "austria",
    "linz": "austria",
    "brussels": "belgium",
    "antwerp": "belgium",
    "ghent": "belgium",
    "prague": "czech republic",
    "praha": "czech republic",
    "brno": "czech republic",
    "ostrava": "czech republic",
    "bucharest": "romania",
    "cluj-napoca": "romania",
    "timisoara": "romania",
    "athens": "greece",
    "thessaloniki": "greece",
    "patras": "greece",
    "budapest": "hungary",
    "debrecen": "hungary",
    "szeged": "hungary",
    "copenhagen": "denmark",
    "aarhus": "denmark",
    "odense": "denmark",
    "helsinki": "finland",
    "espoo": "finland",
    "tampere": "finland",
    "bratislava": "slovakia",
    "kosice": "slovakia",
    "sofia": "bulgaria",
    "plovdiv": "bulgaria",
    "varna": "bulgaria",
    "riga": "latvia",
    "tallinn": "estonia",
    "vilnius": "lithuania",
    "zagreb": "croatia",
    "dubrovnik": "croatia",
    "ljubljana": "slovenia",
    "nicosia": "cyprus",
    "valletta": "malta",
    # Największe miasta mapujące bezpośrednio na kraje EOG (EEA)
    "oslo": "norway",
    "bergen": "norway",
    "reykjavik": "iceland",
}

NON_EU_REGION_CUSTOM = (
    "americas",
    "north america",
    "latam",
    "apac",
)

NON_EU_SCOPE_TITLE_PHRASES = (
    "united states",
    "us only",
    "u.s.",
    "usa",
    "canada",
    # MIDDLE EAST & WESTERN ASIA
    "bahrain",
    "iraq",
    "israel",
    "jordan",
    "kuwait",
    "lebanon",
    "oman",
    "palestine",
    "qatar",
    "saudi arabia",
    "syria",
    "turkey",
    "united arab emirates",
    "yemen",
    # NORTH AFRICA
    "algeria",
    "egypt",
    "libya",
    "morocco",
    "tunisia",
    "western sahara",
    # SUB-SAHARAN AFRICA
    "angola",
    "benin",
    "botswana",
    "burkina faso",
    "burundi",
    "cabo verde",
    "cameroon",
    "central african republic",
    "chad",
    "comoros",
    "congo",
    "democratic republic of the congo",
    "djibouti",
    "rquatorial Guinea",
    "rritrea",
    "rswatini",
    "rthiopia",
    "gabon",
    "gambia",
    "ghana",
    "guinea",
    "guinea-bissau",
    "ivory coast",
    "Kkenya",
    "lesotho",
    "liberia",
    "madagascar",
    "malawi",
    "mali",
    "mauritania",
    "mauritius",
    "mozambique",
    "namibia",
    "niger",
    "nigeria",
    "rwanda",
    "sao Tome and principe",
    "senegal",
    "seychelles",
    "sierra Leone",
    "somalia",
    "south Africa",
    "south Sudan",
    "sudan",
    "tanzania",
    "togo",
    "uganda",
    "zambia",
    "zimbabwe",
)

NON_EU_SCOPE_TOKENS = {
    "us",
    "usa",
    "canada",
}

EOG_COUNTRIES = (
    "norway",
    "iceland",
    "liechtenstein",
)

EU_REGION_KEYWORDS = (
    "europe",
    "within eu",
    "eu-wide",
    "eu wide",
    "europe-wide",
    "europe wide",
    "europe only",
    "european economic area",
    "eea",
    "european union",
    "iberia",
)

US_STRONG_SIGNALS = (
    "united states only",
    "usa only",
    "u.s. only",
    "us only",
    "remote us",
    "remote in the us",
    "remote within the us",
    "remote within united states",
    "us-based only",
    "us based only",
    "u.s.-based only",
    "must live in the us",
    "must be in the us",
    "must reside in the us",
    "must be based in the us",
    "must be us-based",
    "us residents only",
    "within the united states",
    "within united states",
    "u.s.-based",
    "us-based",
    "united states",
    "u.s.",
    "usa",
)

CANADA_STRONG_SIGNALS = (
    "canada only",
    "canadian residents only",
    "remote canada",
    "remote in canada",
    "canada-based",
    "canada based",
    "must live in canada",
    "must be based in canada",
    "must reside in canada",
    "within canada",
    "canada",
)

APAC_STRONG_SIGNALS = (
    "apac only",
    "within apac",
    "asia pacific",
    "apac",
)

AUSTRALIA_STRONG_SIGNALS = (
    "australia only",
    "australia-based",
    "australia based",
    "must live in australia",
    "within australia",
    "australia",
)

INDIA_STRONG_SIGNALS = (
    "india only",
    "india-based",
    "india based",
    "must live in india",
    "within india",
    "india",
)

LATAM_STRONG_SIGNALS = (
    "latam only",
    "within latam",
    "latin america",
    "latam",
)

NON_EU_RESTRICTED = tuple(
    dict.fromkeys(
        (
            *US_STRONG_SIGNALS,
            *CANADA_STRONG_SIGNALS,
            *APAC_STRONG_SIGNALS,
            *AUSTRALIA_STRONG_SIGNALS,
            *INDIA_STRONG_SIGNALS,
            *LATAM_STRONG_SIGNALS,
            "north america only",
        )
    )
)

# Deliberately excludes ambiguous short forms (IN, OR, ME, HI).
US_STATE_CODES = (
    "al",
    "ak",
    "az",
    "ar",
    "ca",
    "co",
    "ct",
    "dc",
    "de",
    "fl",
    "ga",
    "ia",
    "id",
    "il",
    "ks",
    "ky",
    "la",
    "ma",
    "md",
    "mi",
    "mn",
    "mo",
    "ms",
    "mt",
    "nc",
    "nd",
    "ne",
    "nh",
    "nj",
    "nm",
    "nv",
    "ny",
    "oh",
    "ok",
    "pa",
    "ri",
    "sc",
    "sd",
    "tn",
    "tx",
    "ut",
    "va",
    "vt",
    "wa",
    "wi",
    "wv",
    "wy",
)

US_STATE_SIGNAL_THRESHOLD = 3
