ALTER TABLE jobs ADD COLUMN IF NOT EXISTS salary_min REAL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS salary_max REAL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS salary_currency VARCHAR(10);
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS salary_period VARCHAR(20);
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS salary_source VARCHAR(50);
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS salary_min_eur REAL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS salary_max_eur REAL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS salary_transparency_status TEXT;