name: Check Commit Messages

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  commitizen-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Wymagane, aby pobrać całą historię PR-a
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Check commit messages with Commitizen
        run: |
          pip install commitizen
          cz check --rev-range ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}