name: Terraform Plan

on:
  pull_request:
    paths:
      - "infra/**"

permissions:
  contents: read
  pull-requests: read

jobs:

  plan-dev:
    if: github.base_ref == 'develop'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/gcp/dev

    env:
      TF_VAR_project_id: dev-openjobseu
      TF_VAR_image: europe-north1-docker.pkg.dev/dev-openjobseu/dev-openjobseu/dev-openjobseu:pr-placeholder
      TF_VAR_google_client_id: ${{ secrets.DEV_GOOGLE_CLIENT_ID }}
      TF_VAR_google_client_secret: ${{ secrets.DEV_GOOGLE_CLIENT_SECRET }}
      TF_VAR_session_secret_key: ${{ secrets.DEV_SESSION_SECRET_KEY }}
      TF_VAR_allowed_auth_email: ${{ secrets.DEV_ALLOWED_AUTH_EMAIL }}
      TF_VAR_google_api_key: ${{ secrets.DEV_GOOGLE_API_KEY }}
      TF_VAR_google_cse_id: ${{ secrets.DEV_GOOGLE_CSE_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_DEV }}

      - run: terraform init -input=false
      - run: terraform validate
      - run: terraform plan -input=false


  plan-prod:
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/gcp/prod

    env:
      TF_VAR_project_id: openjobseu
      TF_VAR_image: europe-north1-docker.pkg.dev/openjobseu/openjobseu/openjobseu:pr-placeholder
      TF_VAR_google_client_id: ${{ secrets.PROD_GOOGLE_CLIENT_ID }}
      TF_VAR_google_client_secret: ${{ secrets.PROD_GOOGLE_CLIENT_SECRET }}
      TF_VAR_session_secret_key: ${{ secrets.PROD_SESSION_SECRET_KEY }}
      TF_VAR_allowed_auth_email: ${{ secrets.PROD_ALLOWED_AUTH_EMAIL }}
      TF_VAR_google_api_key: ${{ secrets.PROD_GOOGLE_API_KEY }}
      TF_VAR_google_cse_id: ${{ secrets.PROD_GOOGLE_CSE_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_PROD }}

      - run: terraform init -input=false
      - run: terraform validate
      - run: terraform plan -input=false
