name: Terraform Plan

on:
  pull_request:
    paths:
      - "infra/**"

permissions:
  contents: read
  pull-requests: read

jobs:

  plan-dev:
    if: github.base_ref == 'develop'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/gcp/dev

    env:
      TF_VAR_project_id: dev-openjobseu
      TF_VAR_image: europe-north1-docker.pkg.dev/dev-openjobseu/dev-openjobseu/dev-openjobseu:pr-placeholder
      TF_VAR_google_api_key: "dummy-api-key"
      TF_VAR_google_cse_id: "dummy-cse-id"

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_DEV }}

      - run: terraform init -input=false
      - run: terraform validate
      - run: terraform plan -input=false


  plan-prod:
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/gcp/prod

    env:
      TF_VAR_project_id: openjobseu
      TF_VAR_image: europe-north1-docker.pkg.dev/openjobseu/openjobseu/openjobseu:pr-placeholder
      TF_VAR_google_client_id: "dummy-client-id"
      TF_VAR_google_client_secret: "dummy-client-secret"
      TF_VAR_session_secret_key: "dummy-session-key"
      TF_VAR_allowed_auth_email: "dummy@example.com"
      TF_VAR_google_api_key: "dummy-api-key"
      TF_VAR_google_cse_id: "dummy-cse-id"

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_PROD }}

      - run: terraform init -input=false
      - run: terraform validate
      - run: terraform plan -input=false
