name: Terraform Plan

on:
  pull_request:
    branches: [main, develop]
    paths:
      - "infra/**"

concurrency:
  group: terraform-plan-${{ github.event.pull_request.number }}-${{ github.base_ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read
  id-token: write

jobs:

  plan-dev:
    if: github.base_ref == 'develop'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/gcp/dev

    env:
      TF_VAR_project_id: dev-openjobseu
      TF_VAR_image: europe-north1-docker.pkg.dev/dev-openjobseu/dev-openjobseu/dev-openjobseu:pr-placeholder
      TF_VAR_google_client_id: ${{ secrets.DEV_GOOGLE_CLIENT_ID }}
      TF_VAR_google_client_secret: ${{ secrets.DEV_GOOGLE_CLIENT_SECRET }}
      TF_VAR_session_secret_key: ${{ secrets.DEV_SESSION_SECRET_KEY }}
      TF_VAR_allowed_auth_email: ${{ secrets.DEV_ALLOWED_AUTH_EMAIL }}
      TF_VAR_google_api_key: ${{ secrets.DEV_GOOGLE_API_KEY }}
      TF_VAR_google_cse_id: ${{ secrets.DEV_GOOGLE_CSE_ID }}
      TF_VAR_serper_api_key: ${{ secrets.DEV_SERPER_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER_DEV }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT_TERRAFORM_PLAN_DEV }}

      - run: terraform init -input=false
      - run: terraform validate
      - run: terraform plan -input=false


  plan-prod:
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/gcp/prod

    env:
      TF_VAR_project_id: openjobseu
      TF_VAR_image: europe-north1-docker.pkg.dev/openjobseu/openjobseu/openjobseu:pr-placeholder
      TF_VAR_google_client_id: ${{ secrets.PROD_GOOGLE_CLIENT_ID }}
      TF_VAR_google_client_secret: ${{ secrets.PROD_GOOGLE_CLIENT_SECRET }}
      TF_VAR_session_secret_key: ${{ secrets.PROD_SESSION_SECRET_KEY }}
      TF_VAR_allowed_auth_email: ${{ secrets.PROD_ALLOWED_AUTH_EMAIL }}
      TF_VAR_google_api_key: ${{ secrets.PROD_GOOGLE_API_KEY }}
      TF_VAR_google_cse_id: ${{ secrets.PROD_GOOGLE_CSE_ID }}
      TF_VAR_serper_api_key: ${{ secrets.PROD_SERPER_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER_PROD }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT_TERRAFORM_PLAN_PROD }}

      - run: terraform init -input=false
      - run: terraform validate
      - run: terraform plan -input=false
